exclude:     [CONTRIBUTING.md, Gemfile, Gemfile.lock, LICENSE, README.md, TERMS.md]
permalink:   /articles/:title/
highlighter: rouge
markdown:    kramdown

title: ./
url: "https://sangseu.github.io/"
description: "Learn about the technology work the Consumer Financial Protection Bureau undertakes to support its mission."
